= Inpatient Quick Reference
Cincinnati Children's
v0.1, October 28, 2024
:data-uri:
:icons: font
:toclevels: 3



****
icon:hospital[] _Acute/Critical Care_
****

== Admission
Oct 28, 2024 at 5:45 PM - 7:45 PM
Andy Homework

* [ ] <<language-preference-id,Identify language preferences>>.
* [ ] <<accessing_inperson_interpreters,Schedule in-person interpreters>> for rounds.
* [ ] If necessary, review <<family-friend,when family/friends can interpret>>.

== Rounds

Plan in advance for rounds by:

1. Engaging the family:
** Explain how rounds work on your unit and explore their communication preferences. What parts of the rounding conversation do they want to be involved in?
** What time will they be available for rounds?
2. <<accessing_inperson_interpreters,Requesting an in-person interpreter>>. Consider: 
** Does your team or unit need to work with the in-person intrerpreter for multiple patients?
** Will other members of your multidisciplinary team need to time work with the in-person interpreter during that visit
** Units that designate a role that is responsible for this have more success with obtaining in-person interpreters.

When a family is not at bedside, consider <<outbound-phone-calls,
calling them with a phone interpreter>>.


=== Rounding with Phone or Video Intepreters
<<Phone>> and <<video>> interpreters cannot interpret simultaneously. Chunking and turn-taking are required.


=== MyRounds
MyRounds is only available in English. Explain this to families who use languages other than English and enroll them if they would like to use MyRounds in English.


== Discharge

* [ ] <<accessing_inperson_interpreters,Schedule in-person interpreters>> for teaching.
* [ ] <<accessing_inperson_interpreters,Schedule in-person interpreters>> for reviewing discharge instructions.
* [ ] <<written,Translate>> discharge instructions and, if applicable, medication lists.
* [ ] Provide <<external,appropriate external resources>>.
    