= Language Access Quality Improvement[[qi]]

Any language access quality improvement projects should involve staff from Language Access Services. Contact interpreterservices@cchmc.org for support.

In creating this plan, we compiled a https://cchmc-my.sharepoint.com/:w:/g/personal/andrew_schwieter_cchmc_org/EZj9oznQBwVPqijKAX7otgwBzuLtD4eQVVLCQ7im0fTQiQ?e=OuhGrA[list of possible improvement projects].

There is also a Spanish-Speaking Family Forum to discuss issues and co-create solutions. Contact mailto:Karla.Eysoldt@cchmc.org[Karla Eysoldt] to get on the agenda.

== Current and Past QI Projects

* icon:hospital[] Acute/Critical Care:
** https://doi.org/10.1542/hpeds.2021-005981[Improving Discharge Instructions for Hospitalized Children with Limited English Proficiency]
** mailto:Sally.Muskett@cchmc.org[Sally Muskett]'s RCIC NICU Discharge
** Multi-language patient welcome videos
* icon:store[] Ambulatory:
** Telehealth Spanish QI lead by Courtney Sump
** DEI Fellows (Audiology, Speech, OT/PT)
* icon:plus[] Emergency Services:
** Equity dashboard
** https://pxjournal.org/journal/vol11/iss3/16/[A Quality Improvement Initiative Using Discharge Education Videos to Improve Communication with Families in a Pediatric Urgent Care]
