= Written Communication [[written]]

[.filter-acute-critical-care.filter-home-health.filter-mental-health]
== Acute/Critical Care, Home Health, and Inpatient/Residential Mental Health [[inpatient]]

****
icon:hospital[] _Acute/Critical Care_  icon:house[] _Home Health_  icon:brain[] _Inpatient/Residential Mental Health_

Consider literacy and health literacy before providing written translations. These needs are documented in the https://cchmc.service-now.com/is?id=kb_article_view&sysparm_article=KB0012321[Learning Assessment].

Translate commonly-used patient- and family-facing forms, resources, education materials into languages that are used by 1% or more of patients seen on the unit.

Provide discharge instructions in the preferred language of each caregiver whenever possible. Follow the https://cchmc.service-now.com/is?id=kb_article_view&sysparm_article=KB0013699[Epic Job Aid]. In the absence of translated discharge instructions, we can:

1. Ask the family to use their smartphone's Voice Recorder app to record the conversation you have with the help of an interpreter. That would allow them to listen back to the instructions at home.

   * A video recording is also permitted as long as any staff member who is recorded gives the family verbal permission to record them. See https://cchmc.navexone.com/content/dotNet/documents/?docid=9449[Policy MCP-G-114] for more details.

2. Only communicate verbally with help of an interpreter, relying on teach-back to ensure understanding. Provide pen and paper and ask the parent to write down key information.

3. Ask the in-person interpeter to provide written translation of short discharge instructions.

Do not translate progress notes or test results. To provide this in writing to families, summarize them in a letter using words the family can easily understand and request translation of the letter via the https://centerlink.cchmc.org/forms/interpreter-services/written-translation-request[Translation Request Form on CenterLink].

Translation is not currently available for MyChart messaging, text messages (except for automated reminder messages), and emails to families. If you receive a message in a language other than English, request a translation from the https://centerlink.cchmc.org/forms/interpreter-services/written-translation-request[Translation Request Form on CenterLink].

****

[.filter-home-health]
****
icon:home[] _Home Health_

There is not a safe way to translate text messages to and from families. To communicate our expected arrival times, our options are phone calls or sending the text messages in English. Present these options to families and let them choose.

****

[.filter-emergency-services]
== Emergency Services

****
icon:plus[] _Emergency Services_

When providing any documents to someone who sometimes uses a language other than English, ask the person what language(s) they would like the particular documents in.

Consider assessing health literacy by asking a question such as:

   * "How confident are you filling out medical forms by yourself?”
   * "How often do you have problems learning about your medical condition because of difficulty with written information?"

Translate commonly-used patient- and family-facing forms, resources, https://centerlink.cchmc.org/patient-services/patient-and-family-education/home[education materials] into languages that are used by 1% or more of patients seen in Emergency Services.

Provide discharge instructions in the preferred language of each caregiver whenever possible with AVS attachments. In the absence of translated discharge instructions, we can:

1. Ask the family to use their smartphone's Voice Recorder app to record the conversation you have with the help of an interpreter. That would allow them to listen back to the instructions at home.

   a. A video recording is also permitted as long as any staff member who is recorded gives the family verbal permission to do so.

2. Only communicate verbally with help of an interpreter, relying on teach-back to ensure understanding. Provide pen and paper and ask the parent to write down key information.

3. Ask the in-person interpeter to provide written translation of short discharge instructions.

****

[.filter-periop]
== Periop

****
icon:syringe[] _Periop_

When providing any documents to someone who sometimes uses a language other than English, ask the person what language(s) they would like the particular documents in.

Consider assessing health literacy by asking a question such as:

   * "How confident are you filling out medical forms by yourself?”
   * "How often do you have problems learning about your medical condition because of difficulty with written information?"

Translate commonly-used patient- and family-facing forms, resources, https://centerlink.cchmc.org/patient-services/patient-and-family-education/home[education materials] into languages that are used by 1% or more of patients seen in Periop.

Provide discharge instructions in the preferred language of each caregiver whenever possible with Knowing Notes. In the absence of translated discharge instructions, we can:

1. Ask the family to use their smartphone's Voice Recorder app to record the conversation you have with the help of an interpreter. That would allow them to listen back to the instructions at home.

   a. A video recording is also permitted as long as any staff member who is recorded gives the family verbal permission to do so.

2. Only communicate verbally with help of an interpreter, relying on teach-back to ensure understanding. Provide pen and paper and ask the parent to write down key information.

3. Ask the in-person interpeter to provide written translation of short discharge instructions.

****

[.filter-ambulatory.filter-mental-health]
== Ambulatory and Outpatient Mental Health

****
icon:store[] _Ambulatory_  icon:brain[] _Outpatient Mental Health_

When providing any documents to someone who sometimes uses a language other than English, ask the person what language(s) they would like the particular documents in.

Consider assessing health literacy by asking a question such as:

   * "How confident are you filling out medical forms by yourself?”
   * "How often do you have problems learning about your medical condition because of difficulty with written information?"

Translate commonly-used patient- and family-facing forms, resources, https://centerlink.cchmc.org/patient-services/patient-and-family-education/home[education materials] into languages that are used by 1% or more of patients seen in the clinic.

[discrete]
=== Patient/Encounter Specific

Do not request translation for AVSs. Instead communicate verbally. Use https://cchmc.service-now.com/is?id=kb_article_view&sysparm_article=KB0013699[Epic templated translations] when available.

Do not translate progress notes, reports, or test results. To provide this in writing to families, summarize them in a letter using words the family can easily understand and request translation of the letter via the https://centerlink.cchmc.org/forms/interpreter-services/written-translation-request[Translation Request Form on CenterLink].

Translation is not currently available for sending MyChart message, text messages, or emails to families. If you receive a message in a language other than English, call the family with a xref:verbal.adoc#outbound-phone-calls[phone interpreter] or request a translation from the https://centerlink.cchmc.org/forms/interpreter-services/written-translation-request[Translation Request Form on CenterLink].

For any other patient/encounter specific translations, contact translations@cchmc.org to start the process. We will consider the importance of the materials and other resources which could serve this purpose.
****

== AI or Machine Translation

Do not use Google Translate, CoPilot, ChatGPT, or any other automated translation tool. It is https://www.hhs.gov/sites/default/files/ocr-dcl-section-1557-language-access.pdf[against federal law] because it is https://pmc.ncbi.nlm.nih.gov/articles/PMC11729812/[not accurate enough] and therefore https://jamanetwork.com/journals/jama/fullarticle/2823653[puts patient safety at risk].

== Medical Records in Languages other than English

International patients should arrive through https://centerlink.cchmc.org/managers/destination-excellence-de/destination-excellence[Destination Excellence]. Their process requires that patients provide translations of relevant medical records before we accept them as Cincinnati Children's patients.

For other patients, request translation of the specific portion(s) of the records you need via the https://centerlink.cchmc.org/forms/interpreter-services/written-translation-request[Translation Request Form on CenterLink].





== Forms, Surveys, and Screeners

Give people paper and digital forms in the language they want the forms to be in. When that language is not available, ask the questions verbally.

[.filter-ambulatory]
****
icon:store[] _Ambulatory_

If giving these documents at Registration, tell the family we will ask the questions verbally during the clinical visit.

****

== Existing Translations

Useful translations include:


* The https://www.cincinnatichildrens.org/patient-resources/app[Cincinnati Children's app] is available in Spanish and Arabic
** https://atobe.app/photo-route?buildingId=30&homepage=true&routeLang=en[Wayfinding on the web] is also availabe in Spanish and Arabic, including QR codes for families to scan.
* https://centerlink.cchmc.org/echirp/patient-family-ed/knowing-notes[Knowing Notes]
* https://centerlink.cchmc.org/echirp/periop/perioperative-patient-family-education[Perioperative Patient & Family Education for Procedure (Surgery)]
* https://www.cincinnatichildrens.org/patients/visit/visiting-guidelines/rights[Visitor Guide / Patient Rights & Responsibilities]
* https://cchmc.navexone.com/content/Search/Documents[Forms and Consents for Surgical/Medical Procedure]
* Cards for https://centerlink.cchmc.org/department/interpreter-services/dial-direct-interpreter-access-line[Direct Interpreter Access Lines] are available by from interpreterservices@cchmc.org
* https://www.cincinnatichildrens.org/espanol/visitas-por-video/instrucciones[Spanish telehealth visit instructions]
* icon:hospital[] Acute/Critical Care:
** https://centerlink.cchmc.org/echirp/nutrition/paper-menus[Patient menus]
** https://www.cincinnatichildrens.org/patient-resources/inpatient-visits[Family Guide]
** Welcome videos
* icon:store[] Ambulatory:
** https://centerlink.cchmc.org/department/gen-peds/handouts-and-resources[GenPeds Provider and Patient Resources]
* icon:plus[] Emergency Services:
** AVS attachments
* icon:syringe[] Periop:
** https://centerlink.cchmc.org/echirp/patient-family-ed/knowing-notes/periop-surgery[Knowing Notes]
** The Periop folder is available in Spanish and Arabic
* icon:house[] Home Health:
** HHC Folders in Spanish and Arabic


== Medication Labels

The Cincinnati Children's Pharmacies can print labels in Spanish for common sigs. Outside pharmacies can print labels in many languages for common sigs.

Some families may not be familiar with the concept of refills.

[.filter-acute-critical-care]
****
icon:hospital[] _Acute/Critical Care_

Inpatient pharmacists can create bilingual MedActionPlans for patients with complicated medication needs.

****

== Digital Touchpoints

MyChart is currently not available in Spanish.

New Cincinnati Children's owned or purchased apps, webpages, or other digital communication should be designed to support Spanish for all patient- and family-facing communication within 12 months of going live. Additional languages and existing digital touchpoints can be considered on a case-by-case basis. Contact translations@cchmc.org for support.

When the language you need isn't available, find a different way to provide the value of the app, webpage or digital communication.

== External Resources [[external]]

Before sharing an external resource with a family such as a website, app, book, or video, check if it is available in their language. If it is not, consider finding other resources for the family, or asking if the particular resource will be helpful despite only being available in English.

The same goes for providing phone numbers to external organizations. Check to see if they offer interpreter services before referring the family.

[.filter-emergency-services]
****
icon:plus[] _Emergency Services_

The Spanish resource list LINK NEEDED addresses many common needs.

****

== People with Blindness and Visual Impairments

Braille materials can be created when specifically requested by a patient or person accompanying a patient. Contact translations@cchmc.org for support.

Many people who are blind prefer using digital documents and a screen reader. Provide digital documents upon request. For help, contact translations@cchmc.org.
