site:
  title: Language Access Plan
  start_page: LAP::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: ./ui-bundle
    snapshot: true
antora:
  extensions:
  - '@antora/lunr-extension'
asciidoc:
  attributes:
    icons: font
    # Optionally specify which icon set (FontAwesome 5+)
    icon-set: fas # For solid icons (or use fab for brands, far for regular)